#!/bin/bash
uname -a > test1.txt
cat test1.txt
echo "This is our first scrip"
echo "we gonna imput some parameters called $PARAMS"
NUM=$(($FIRSTNUMBER + $SECONDNUMBER))
echo "$NUM"
echo "$NUM" >> test1.txt
echo "sammy-sosa is so good to me"
systemctl status jenkins >> test1.txt
echo "Thank you Jesus" > test2.txt
